# Generated by Django 4.2.7 on 2023-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
