# Generated by Django 4.2.7 on 2023-12-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
