# Generated by Django 4.2.7 on 2023-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='timing',
            field=models.CharField(max_length=20),
        ),
    ]
