# Generated by Django 4.2.7 on 2024-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='current_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_participants',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
