# Generated by Django 4.2.7 on 2024-01-15 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_current_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(default=25))]),
        ),
    ]
