# Generated by Django 4.2.7 on 2023-12-05 14:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_rename_announcements_announcement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
                ('specials', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
