# Generated by Django 4.2.7 on 2023-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_managers_announcement_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
