# Generated by Django 4.2.7 on 2024-01-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_content_type_announcement_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='object_id',
        ),
    ]
