# Generated by Django 4.2.7 on 2024-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_announcement_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_ticket',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
