# Generated by Django 4.2.7 on 2024-01-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_announcement_announcement_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_ticket',
            new_name='announcement_id',
        ),
    ]
