# Generated by Django 4.2.7 on 2024-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_rename_announcement_ticket_announcement_announcement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
