# Generated by Django 4.2.7 on 2024-01-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_discount_price'),
        ('programs', '0001_initial'),
        ('schedule', '0003_alter_schedule_timing'),
        ('announcements', '0010_alter_announcement_announcement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.exercise'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='pricing.pricing'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.schedule'),
        ),
    ]
