# Generated by Django 4.2.7 on 2024-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_alter_announcement_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Exercise, Specials and More', 'Exercise, Specials and More'), ('Schedule Updates', 'Schedule Updates'), ('DISCOUNTS, DEALS, and PROMOS!', 'DISCOUNTS, DEALS, and PROMOS!')], max_length=38),
        ),
    ]
