# Generated by Django 4.2.7 on 2024-01-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_alter_announcement_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
