# Generated by Django 4.2.7 on 2024-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_rename_exercise_announcement_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
